on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run composer install
      uses: php-actions/composer@v6
      with:
       dev: no
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.premiump.netbomb.pl
        username: konrad@muzungu.pl
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/testghactions
